services:
  - type: web
    name: book-review-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
