services:
  - type: web
    name: book-review-frontend
    env: node
    plan: free
    rootDir: Frontend              
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html




